[package]
name = "alpha"
version = "0.2.0"
edition = "2024"
authors = ["ElseJJ"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "alpha"
crate-type = ["cdylib", "rlib"]

[features]
default = ["parallel", "python"]
parallel = ["rayon"]
python = ["pyo3", "numpy", "pyo3-log", "parallel"]

[dependencies]
pyo3 = { version = "0.28", features = ["abi3"], optional = true }
pyo3-log = { version = "0.13", optional = true }
numpy = { version = "0.28", optional = true }
rayon = { version = "1.11", optional = true }
thiserror = "2"
num-traits = "0.2"
log = "0.4"


[build-dependencies]
anyhow = "1"
